#!/bin/bash

configure_ip_forwarding() {
    log_info "Configuring IP forwarding..."
    
    get_sysctl_method
    
    if [ "$SYSCTL_METHOD" = "sysctl.conf" ]; then
        configure_sysctl_conf
    else
        configure_sysctl_d
    fi
    
    apply_sysctl
    
    verify_ip_forwarding
}

configure_sysctl_conf() {
    local sysctl_file="/etc/sysctl.conf"
    
    log_debug "Configuring $sysctl_file"
    
    if [ ! -f "$sysctl_file" ]; then
        log_warn "$sysctl_file does not exist, creating it..."
        touch "$sysctl_file"
    fi
    
    if grep -q "^net.ipv4.ip_forward" "$sysctl_file" 2>/dev/null; then
        sed -i 's/^net.ipv4.ip_forward.*/net.ipv4.ip_forward=1/' "$sysctl_file"
        log_debug "Updated existing net.ipv4.ip_forward entry"
    elif grep -q "^#net.ipv4.ip_forward" "$sysctl_file" 2>/dev/null; then
        sed -i 's/^#net.ipv4.ip_forward.*/net.ipv4.ip_forward=1/' "$sysctl_file"
        log_debug "Uncommented net.ipv4.ip_forward entry"
    else
        echo "net.ipv4.ip_forward=1" >> "$sysctl_file"
        log_debug "Added net.ipv4.ip_forward entry"
    fi
    
    if ! grep -q "^net.ipv6.conf.all.forwarding" "$sysctl_file" 2>/dev/null; then
        echo "net.ipv6.conf.all.forwarding=1" >> "$sysctl_file"
        log_debug "Added net.ipv6.conf.all.forwarding entry"
    else
        sed -i 's/^net.ipv6.conf.all.forwarding.*/net.ipv6.conf.all.forwarding=1/' "$sysctl_file"
    fi
    
    log_success "Updated $sysctl_file"
}

configure_sysctl_d() {
    local sysctl_dir="/etc/sysctl.d"
    local sysctl_file="$sysctl_dir/99-wireguard.conf"
    
    log_debug "Creating $sysctl_file"
    
    mkdir -p "$sysctl_dir"
    
    cat > "$sysctl_file" << EOF
# WireGuard VPN IP Forwarding Configuration
# Generated by WireGuard Installer on $(date)
net.ipv4.ip_forward = 1
net.ipv6.conf.all.forwarding = 1
EOF
    
    chmod 644 "$sysctl_file"
    
    log_success "Created $sysctl_file"
}

apply_sysctl() {
    log_info "Applying sysctl settings..."
    
    if [ "$SYSCTL_METHOD" = "sysctl.d" ]; then
        sysctl --system 2>/dev/null || {
            sysctl -p /etc/sysctl.d/99-wireguard.conf 2>/dev/null || {
                log_warn "Could not apply sysctl settings via sysctl --system"
            }
        }
    else
        sysctl -p 2>/dev/null || {
            log_warn "Could not apply sysctl settings via sysctl -p"
        }
    fi
    
    sysctl -w net.ipv4.ip_forward=1 2>/dev/null || true
    sysctl -w net.ipv6.conf.all.forwarding=1 2>/dev/null || true
    
    log_success "Applied sysctl settings"
}

verify_ip_forwarding() {
    local ipv4_forward
    ipv4_forward=$(cat /proc/sys/net/ipv4/ip_forward 2>/dev/null)
    
    if [ "$ipv4_forward" = "1" ]; then
        log_success "IPv4 forwarding is enabled"
    else
        log_error "Failed to enable IPv4 forwarding"
        log_error "Current value: $ipv4_forward (expected: 1)"
        return 1
    fi
    
    return 0
}

get_sysctl_status() {
    echo "=== Sysctl Status ==="
    
    echo "IPv4 forwarding: $(cat /proc/sys/net/ipv4/ip_forward 2>/dev/null || echo 'unknown')"
    echo "IPv6 forwarding: $(cat /proc/sys/net/ipv6/conf/all/forwarding 2>/dev/null || echo 'unknown')"
    
    if [ -f /etc/sysctl.d/99-wireguard.conf ]; then
        echo "Config file: /etc/sysctl.d/99-wireguard.conf"
        cat /etc/sysctl.d/99-wireguard.conf
    elif grep -q "ip_forward" /etc/sysctl.conf 2>/dev/null; then
        echo "Config file: /etc/sysctl.conf"
        grep "ip_forward" /etc/sysctl.conf | grep -v "^#"
    else
        echo "No sysctl config found"
    fi
}
